### PR TITLE
2024

### PR DESCRIPTION
**Pull request by anton-seaice**
@paigem @dougiesquire 

If you have time to review these , it would be great.

Notebook reviews are always messy, you probably need to open the notebooks as well as looking at the review link (in the next comment). You should be able to put comments in the review link though :)

The main notebooks are _intake_tutorial.ipynb_ and _large_data.ipynb_ ... don't worry too much about the other stuff.

### CODE REVIEW

**Comment by dougiesquire** [comment]
I finished my review, but the `gitnotebooks` tool sucks and gave me
Screenshot 2024-08-28 at 2 43 06 PM
when I tried to submit. So I'm going to copy all my comments below

**Comment by dougiesquire** [comment]
# `intake_tutorial.ipynb`

General comment: some cells in this notebook are pre-executed and some aren't.

### Introduction to the ACCESS-NRI Intake catalog

"catalog a show" -> "catalog and show"
"this ACCESS-Hive page" link is broken

### The motivation
Missing closing bracket at end of third paragraph

### Using the catalog
Bad formatting of `_assets_ are files...`

### Cell 6

Consider replacing with
```
catalog.search(model="ACCESS-*").df.model.unique()
```
for clarity

### Finding a variable

"catalog dataframe view" -> "datastore dataframe view"

### Cell 15
Datasets are not defined by `file_id` alone. Use
```
ocn_1mon_search.keys()
```
here instead.

### Cell 16

"We want a gridded sea surface salinity, so we will use ocean_month". I think it's clearer to search for `sss` here. How would a general user know to use `ocean_month`?
```
ocn_1mon_search = ocn_1mon_search.search(variable='sss')
```
Also, it dangerous to overwrite `ocn_1mon_search` here. What if a used wanted to go back and try out a different search?

### Comment after cell 16

See above comment about `file_id`. If you want to demonstrate there's only one dataset, it says it in bold at the top.

### Cell 17

I suggest removing this and the following comment and searching for `sss` rather than `ocean_month` as per my comment above.

### Cell 20

`catalog_search` is not defined. I presume this is supposed to be

```
om2_ds = ocn_1mon_search.search(variable='sss').to_dask()
```

### Comment before cell 22

I find this unclear (and the bit about `file_id` is not correct - see above).

Key points are:

- the `to_dask()` method only works if there is one remaining dataset in the datastore
- if there are multiple datasets remaining, you can use `to_dataset_dict()` to open the data (as the error message below says) into a dictionary

### Comment after cell 20

See above comments about `file_id`

**Comment by dougiesquire** [comment]
# `large_data.ipynb`

### Cell 3

If you want to have pre-executed cells, it might be worth rerunning so you don't have this `UserWarning: Port 8787 is already in use.` in your output

### Comment after cell 6

You say "about a second" here, but the timing output above says "1min 12s". The timing above also includes opening and searching the datastore so isn't just the time taken to lazily load.

~Also maybe worth drawing attention to the chunking:~
~"Also, note the chunking of the dask array. By default the ``to_dask()`` method will open the data using the native chunking of the files being opened"~
Found this further below

### Comment before cell 7

Maybe worth emphasizing that plotting will trigger compute, because data is actually needed to make the plot .

### Comment after cell 11 starting with "Our source data"

"These are intial chunksizes set also in the xarray DataArray". This sentence is a little unclear and is not true generally. Maybe change to

"By default, `to_dask()` opens the data using dask chunk sizes that are equal to the native chunking of the source data"

### Cell 12

This cell is not really needed

### Cell 13

This gets a speed benefit over the call from above because things are cached

### Note after cell 13

Add something like "If we wanted dask chunksizes larger than 1 in time, we would have to rechunk in a subsequent step" - see the xarray [chunk method](https://docs.xarray.dev/en/latest/generated/xarray.Dataset.chunk.html)"

### Cell 17

`areat_sum` is actually a dask array here, which makes the calculation below very slow because `areat_sum` gets recomputed for every `i`. Loading `areat_sum` will make this much faster (though it's still a bad approach).

### Cell 20

Maybe worth emphasizing that just doing a mean in time is not a good example of a "calculation that requires all time" because the mean across workers is just a simple weighted sum of the mean on each worker. Doing `.median` is still simple but may show larger benefits from chunking.

**Review by dougiesquire — CHANGES_REQUESTED** [review]
See comments in posts above

**Comment by anton-seaice** [comment]
Thanks dougie! I think I addressed all the comments. I will merge tomorrow morning but no pressure to look again :)

> "We want a gridded sea surface salinity, so we will use ocean_month". I think it's clearer to search for sss here. How would a general user know to use ocean_month?

I was trying to do a demonstration of how to browse / find variables. e.g. how would I know its `sss` and not `surface_salt` or something

**Comment by dougiesquire** [comment]
> I was trying to do a demonstration of how to browse / find variables. e.g. how would I know its sss and not surface_salt or something

You could search on `variable_long_name` or `variable_standard_name` (assuming that metadata exists in the files)?

**Comment by anton-seaice** [comment]
It doesn't quite get me to the end result :

Screenshot 2024-08-29 at 3 56 30 PM

**Comment by dougiesquire** [comment]
Ah, that's an annoying feature of Intake-ESM

**Pull request merged**
